# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0001_state_post_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postflag",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "待处理"),
                    ("resolved", "已处理"),
                    ("ignored", "已忽略"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
